// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace RTA.Automation.CRM
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uIOKButton = this.UITenancyRequestNewTenWindow.UIItemDialog.UIOKButton;
            #endregion

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(40, 14));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIPaymentReferenceNewPWindow.UIPaymentReferenceNewPDocument.UIContentAreaFrame.UIHttpsrcrm51teMSCRMRTDocument.UIAMANDATESTPane.UIItemCustom;
            HtmlDiv uIAMANDATESTPane = this.UIPaymentReferenceNewPWindow.UIPaymentReferenceNewPDocument.UIContentAreaFrame.UIHttpsrcrm51teMSCRMRTDocument.UIAMANDATESTPane;
            #endregion

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(155, 10));

            // Type '{Back}' in 'AMANDA TEST' pane
            Keyboard.SendKeys(uIAMANDATESTPane, this.RecordedMethod2Params.UIAMANDATESTPaneSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// RecordedMethod3
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WinColumnHeader uIExceptionprocesseddaColumnHeader = this.UIBPAYFileExceptions1rWindow.UIItemWindow.UIBPAYFileLineExceptioTable.UIHeaderControlList.UIExceptionprocesseddaColumnHeader;
            #endregion

            // Click 'Exception processed date/time' column header
            Mouse.Click(uIExceptionprocesseddaColumnHeader, new Point(129, 13));
        }
        
        /// <summary>
        /// CRMLogin - Use 'CRMLoginParams' to pass parameters into this method.
        /// </summary>
        public void CRMLogin()
        {
            #region Variable Declarations
            WinEdit uIUsernameEdit = this.UIWindowsSecurityWindow.UIUseanotheraccountListItem.UIUsernameEdit;
            WinEdit uIPasswordEdit = this.UIWindowsSecurityWindow.UIUseanotheraccountListItem.UIPasswordEdit;
            WinButton uIOKButton = this.UIWindowsSecurityWindow.UIWindowsSecurityPane.UIOKButton;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Type 'imstestu13' in 'User name' text box
            uIUsernameEdit.Text = this.CRMLoginParams.UIUsernameEditText;

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(71, 10));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.CRMLoginParams.UIPasswordEditSendKeys, true);

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(43, 18));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        /// <summary>
        /// WindowTitleBar
        /// </summary>
        public void WindowTitleBar()
        {
            #region Variable Declarations
            WinTitleBar uIWindowsSecurityTitleBar = this.UIWindowsSecurityWindow.UIWindowsSecurityTitleBar;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Click 'Windows Security' title bar
            Mouse.Click(uIWindowsSecurityTitleBar, new Point(345, 13));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        /// <summary>
        /// RecordedMethod4
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            WinTitleBar uIWindowsSecurityTitleBar = this.UIWindowsSecurityWindow.UIWindowsSecurityTitleBar;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Click 'Windows Security' title bar
            Mouse.Click(uIWindowsSecurityTitleBar, new Point(220, 13));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        /// <summary>
        /// RecordedMethod5 - Use 'RecordedMethod5Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            WinEdit uIUsernameEdit = this.UIWindowsSecurityWindow.UIUseanotheraccountListItem.UIUsernameEdit;
            WinEdit uIPasswordEdit = this.UIWindowsSecurityWindow.UIUseanotheraccountListItem.UIPasswordEdit;
            WinButton uIOKButton = this.UIWindowsSecurityWindow.UIWindowsSecurityPane.UIOKButton;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Type 'aaa' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod5Params.UIUsernameEditText;

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(100, 5));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RecordedMethod5Params.UIPasswordEditSendKeys, true);

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(34, 6));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        /// <summary>
        /// RecordedMethod6
        /// </summary>
        public void RecordedMethod6()
        {
            #region Variable Declarations
            WinCustom uIItemCustom = this.UIInvestigationCaseIN4Window.UIInvestigationCaseIN4Document.UIItemCustom;
            #endregion

            // Click custom control numbered 5 in 'Investigation Case: IN40031 - Microsoft Dynamics C...' document
            Mouse.Click(uIItemCustom, new Point(128, 151));
        }
        
        /// <summary>
        /// RecordedMethod7 - Use 'RecordedMethod7Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod7()
        {
            #region Variable Declarations
            WinTitleBar uIInvestigationMasterCTitleBar = this.UIInvestigationMasterCWindow.UIInvestigationMasterCTitleBar;
            HtmlDiv uIItemPane = this.UIInvestigationMasterCWindow.UIInvestigationMasterCDocument.UIContentAreaFrame.UIHttpsrcrmsme63ua5555Document.UIItemPane;
            HtmlCustom uILookUpMoreRecordsCustom1 = this.UIInvestigationMasterCWindow.UIInvestigationMasterCDocument.UIContentAreaFrame.UIHttpsrcrmsme63ua5555Document.UILookUpMoreRecordsCustom.UILookUpMoreRecordsCustom1;
            HtmlDiv uITestUserPane = this.UIInvestigationMasterCWindow.UIInvestigationMasterCDocument.UIContentAreaFrame.UIHttpsrcrmsme63ua5555Document.UITestUserPane;
            #endregion

            // Click 'Investigation Master Case: New Investigation Maste...' title bar
            Mouse.Click(uIInvestigationMasterCTitleBar, new Point(1700, 18));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Mouse hover 'Look Up More Records' custom control at (1, 1)
            Mouse.Hover(uILookUpMoreRecordsCustom1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click pane
            Mouse.Click(uIItemPane, new Point(1783, 54));

            // Type '{Back}' in 'Test User' pane
            Keyboard.SendKeys(uITestUserPane, this.RecordedMethod7Params.UITestUserPaneSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual CRMLoginParams CRMLoginParams
        {
            get
            {
                if ((this.mCRMLoginParams == null))
                {
                    this.mCRMLoginParams = new CRMLoginParams();
                }
                return this.mCRMLoginParams;
            }
        }
        
        public virtual RecordedMethod5Params RecordedMethod5Params
        {
            get
            {
                if ((this.mRecordedMethod5Params == null))
                {
                    this.mRecordedMethod5Params = new RecordedMethod5Params();
                }
                return this.mRecordedMethod5Params;
            }
        }
        
        public virtual RecordedMethod7Params RecordedMethod7Params
        {
            get
            {
                if ((this.mRecordedMethod7Params == null))
                {
                    this.mRecordedMethod7Params = new RecordedMethod7Params();
                }
                return this.mRecordedMethod7Params;
            }
        }
        
        public UITenancyRequestNewTenWindow UITenancyRequestNewTenWindow
        {
            get
            {
                if ((this.mUITenancyRequestNewTenWindow == null))
                {
                    this.mUITenancyRequestNewTenWindow = new UITenancyRequestNewTenWindow();
                }
                return this.mUITenancyRequestNewTenWindow;
            }
        }
        
        public UIPaymentReferenceNewPWindow UIPaymentReferenceNewPWindow
        {
            get
            {
                if ((this.mUIPaymentReferenceNewPWindow == null))
                {
                    this.mUIPaymentReferenceNewPWindow = new UIPaymentReferenceNewPWindow();
                }
                return this.mUIPaymentReferenceNewPWindow;
            }
        }
        
        public UIBPAYFileExceptions1rWindow UIBPAYFileExceptions1rWindow
        {
            get
            {
                if ((this.mUIBPAYFileExceptions1rWindow == null))
                {
                    this.mUIBPAYFileExceptions1rWindow = new UIBPAYFileExceptions1rWindow();
                }
                return this.mUIBPAYFileExceptions1rWindow;
            }
        }
        
        public UIWindowsSecurityWindow UIWindowsSecurityWindow
        {
            get
            {
                if ((this.mUIWindowsSecurityWindow == null))
                {
                    this.mUIWindowsSecurityWindow = new UIWindowsSecurityWindow();
                }
                return this.mUIWindowsSecurityWindow;
            }
        }
        
        public UIInvestigationCaseIN4Window UIInvestigationCaseIN4Window
        {
            get
            {
                if ((this.mUIInvestigationCaseIN4Window == null))
                {
                    this.mUIInvestigationCaseIN4Window = new UIInvestigationCaseIN4Window();
                }
                return this.mUIInvestigationCaseIN4Window;
            }
        }
        
        public UIInvestigationMasterCWindow UIInvestigationMasterCWindow
        {
            get
            {
                if ((this.mUIInvestigationMasterCWindow == null))
                {
                    this.mUIInvestigationMasterCWindow = new UIInvestigationMasterCWindow();
                }
                return this.mUIInvestigationMasterCWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private CRMLoginParams mCRMLoginParams;
        
        private RecordedMethod5Params mRecordedMethod5Params;
        
        private RecordedMethod7Params mRecordedMethod7Params;
        
        private UITenancyRequestNewTenWindow mUITenancyRequestNewTenWindow;
        
        private UIPaymentReferenceNewPWindow mUIPaymentReferenceNewPWindow;
        
        private UIBPAYFileExceptions1rWindow mUIBPAYFileExceptions1rWindow;
        
        private UIWindowsSecurityWindow mUIWindowsSecurityWindow;
        
        private UIInvestigationCaseIN4Window mUIInvestigationCaseIN4Window;
        
        private UIInvestigationMasterCWindow mUIInvestigationMasterCWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type '{Back}' in 'AMANDA TEST' pane
        /// </summary>
        public string UIAMANDATESTPaneSendKeys = "{Back}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CRMLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class CRMLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'imstestu13' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "imstestu13";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "mBQq9cL71wNZ1SmHdsLbXt0PFkC/WTPf";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod5'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod5Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'aaa' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "aaa";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "lVUohJNkd+GmyxnZZiociA==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod7'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod7Params
    {
        
        #region Fields
        /// <summary>
        /// Type '{Back}' in 'Test User' pane
        /// </summary>
        public string UITestUserPaneSendKeys = "{Back}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITenancyRequestNewTenWindow : WinWindow
    {
        
        public UITenancyRequestNewTenWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Tenancy Request: New Tenancy Request - Microsoft Dynamics CRM - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Tenancy Request: New Tenancy Request - Microsoft Dynamics CRM - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIItemDialog UIItemDialog
        {
            get
            {
                if ((this.mUIItemDialog == null))
                {
                    this.mUIItemDialog = new UIItemDialog(this);
                }
                return this.mUIItemDialog;
            }
        }
        #endregion
        
        #region Fields
        private UIItemDialog mUIItemDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemDialog : WinControl
    {
        
        public UIItemDialog(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
            this.WindowTitles.Add("Tenancy Request: New Tenancy Request - Microsoft Dynamics CRM - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Tenancy Request: New Tenancy Request - Microsoft Dynamics CRM - Mozilla Firefox");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPaymentReferenceNewPWindow : BrowserWindow
    {
        
        public UIPaymentReferenceNewPWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Payment Reference: New Payment Reference - Microsoft Dynamics CRM";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIPaymentReferenceNewPDocument UIPaymentReferenceNewPDocument
        {
            get
            {
                if ((this.mUIPaymentReferenceNewPDocument == null))
                {
                    this.mUIPaymentReferenceNewPDocument = new UIPaymentReferenceNewPDocument(this);
                }
                return this.mUIPaymentReferenceNewPDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIPaymentReferenceNewPDocument mUIPaymentReferenceNewPDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPaymentReferenceNewPDocument : HtmlDocument
    {
        
        public UIPaymentReferenceNewPDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Payment Reference: New Payment Reference - Microsoft Dynamics CRM";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MSCRMRTA08/main.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://srcrm51-te/MSCRMRTA08/main.aspx?etc=10052&extraqs=%3f_CreateFromId%3d%257b" +
                "F66E5A4E-58AB-E411-80CB-005056B972E3%257d%26_CreateFromType%3d10061%26etc%3d1005" +
                "2&histKey=714762021&newWindow=true&pagetype=entityrecord#756832897";
            this.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
            #endregion
        }
        
        #region Properties
        public UIContentAreaFrame UIContentAreaFrame
        {
            get
            {
                if ((this.mUIContentAreaFrame == null))
                {
                    this.mUIContentAreaFrame = new UIContentAreaFrame(this);
                }
                return this.mUIContentAreaFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIContentAreaFrame mUIContentAreaFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIContentAreaFrame : HtmlIFrame
    {
        
        public UIContentAreaFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "contentIFrame0";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "contentIFrame0";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = "Content Area";
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"contentIFrame0\" title=\"Content Are";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
            #endregion
        }
        
        #region Properties
        public UIHttpsrcrm51teMSCRMRTDocument UIHttpsrcrm51teMSCRMRTDocument
        {
            get
            {
                if ((this.mUIHttpsrcrm51teMSCRMRTDocument == null))
                {
                    this.mUIHttpsrcrm51teMSCRMRTDocument = new UIHttpsrcrm51teMSCRMRTDocument(this);
                }
                return this.mUIHttpsrcrm51teMSCRMRTDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsrcrm51teMSCRMRTDocument mUIHttpsrcrm51teMSCRMRTDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsrcrm51teMSCRMRTDocument : HtmlDocument
    {
        
        public UIHttpsrcrm51teMSCRMRTDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MSCRMRTA08/_forms/read/page.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://srcrm51-te/MSCRMRTA08/_forms/read/page.aspx?_CreateFromId=%7bF66E5A4E-58AB" +
                "-E411-80CB-005056B972E3%7d&_CreateFromType=10061&etc=10052&pagemode=iframe&theme" +
                "=Outlook15White";
            this.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
            #endregion
        }
        
        #region Properties
        public UIAMANDATESTPane UIAMANDATESTPane
        {
            get
            {
                if ((this.mUIAMANDATESTPane == null))
                {
                    this.mUIAMANDATESTPane = new UIAMANDATESTPane(this);
                }
                return this.mUIAMANDATESTPane;
            }
        }
        #endregion
        
        #region Fields
        private UIAMANDATESTPane mUIAMANDATESTPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAMANDATESTPane : HtmlDiv
    {
        
        public UIAMANDATESTPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "rta_clientid_lookupDiv";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "AMANDA TEST";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-crm-Lookup ms-crm-InlineLookupEdit";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"ms-crm-Lookup ms-crm-InlineLookupEdit\" id=\"rta_clientid_looku" +
                "pDiv\" role=\"list\" ime-mode=\"auto\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "39";
            this.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "UL";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "ms-crm-InlineLookupEdit";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"ms-crm-InlineLookupEdit\"";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Payment Reference: New Payment Reference - Microsoft Dynamics CRM");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBPAYFileExceptions1rWindow : WinWindow
    {
        
        public UIBPAYFileExceptions1rWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "AxTopLevelFrame";
            this.WindowTitles.Add("‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "12290";
            this.WindowTitles.Add("‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎");
            #endregion
        }
        
        #region Properties
        public UIBPAYFileLineExceptioTable UIBPAYFileLineExceptioTable
        {
            get
            {
                if ((this.mUIBPAYFileLineExceptioTable == null))
                {
                    this.mUIBPAYFileLineExceptioTable = new UIBPAYFileLineExceptioTable(this);
                }
                return this.mUIBPAYFileLineExceptioTable;
            }
        }
        #endregion
        
        #region Fields
        private UIBPAYFileLineExceptioTable mUIBPAYFileLineExceptioTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBPAYFileLineExceptioTable : WinTable
    {
        
        public UIBPAYFileLineExceptioTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "BPAYFileLineExceptionGrid";
            this.WindowTitles.Add("‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎");
            #endregion
        }
        
        #region Properties
        public UIHeaderControlList UIHeaderControlList
        {
            get
            {
                if ((this.mUIHeaderControlList == null))
                {
                    this.mUIHeaderControlList = new UIHeaderControlList(this);
                }
                return this.mUIHeaderControlList;
            }
        }
        #endregion
        
        #region Fields
        private UIHeaderControlList mUIHeaderControlList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHeaderControlList : WinList
    {
        
        public UIHeaderControlList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinList.PropertyNames.Name] = "Header Control";
            this.WindowTitles.Add("‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎");
            #endregion
        }
        
        #region Properties
        public WinColumnHeader UIExceptionprocesseddaColumnHeader
        {
            get
            {
                if ((this.mUIExceptionprocesseddaColumnHeader == null))
                {
                    this.mUIExceptionprocesseddaColumnHeader = new WinColumnHeader(this);
                    #region Search Criteria
                    this.mUIExceptionprocesseddaColumnHeader.SearchProperties[WinControl.PropertyNames.Name] = "Exception processed date/time";
                    this.mUIExceptionprocesseddaColumnHeader.WindowTitles.Add("‪BPAY File Exceptions‬ (‎‪1‬ - ‎‪rtb‬)‎");
                    #endregion
                }
                return this.mUIExceptionprocesseddaColumnHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinColumnHeader mUIExceptionprocesseddaColumnHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIWindowsSecurityWindow : WinWindow
    {
        
        public UIWindowsSecurityWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Windows Security";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Windows Security");
            #endregion
        }
        
        #region Properties
        public UIUseanotheraccountListItem UIUseanotheraccountListItem
        {
            get
            {
                if ((this.mUIUseanotheraccountListItem == null))
                {
                    this.mUIUseanotheraccountListItem = new UIUseanotheraccountListItem(this);
                }
                return this.mUIUseanotheraccountListItem;
            }
        }
        
        public UIWindowsSecurityPane UIWindowsSecurityPane
        {
            get
            {
                if ((this.mUIWindowsSecurityPane == null))
                {
                    this.mUIWindowsSecurityPane = new UIWindowsSecurityPane(this);
                }
                return this.mUIWindowsSecurityPane;
            }
        }
        
        public WinTitleBar UIWindowsSecurityTitleBar
        {
            get
            {
                if ((this.mUIWindowsSecurityTitleBar == null))
                {
                    this.mUIWindowsSecurityTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIWindowsSecurityTitleBar.WindowTitles.Add("Windows Security");
                    #endregion
                }
                return this.mUIWindowsSecurityTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIUseanotheraccountListItem mUIUseanotheraccountListItem;
        
        private UIWindowsSecurityPane mUIWindowsSecurityPane;
        
        private WinTitleBar mUIWindowsSecurityTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIUseanotheraccountListItem : WinListItem
    {
        
        public UIUseanotheraccountListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Use another account";
            this.WindowTitles.Add("Windows Security");
            #endregion
        }
        
        #region Properties
        public WinEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "User name";
                    this.mUIUsernameEdit.WindowTitles.Add("Windows Security");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WinEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Windows Security");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIUsernameEdit;
        
        private WinEdit mUIPasswordEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIWindowsSecurityPane : WinPane
    {
        
        public UIWindowsSecurityPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Windows Security";
            this.WindowTitles.Add("Windows Security");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Windows Security");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIInvestigationCaseIN4Window : WinWindow
    {
        
        public UIInvestigationCaseIN4Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Investigation Case: IN40031 - Microsoft Dynamics CRM - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Investigation Case: IN40031 - Microsoft Dynamics CRM - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIInvestigationCaseIN4Document UIInvestigationCaseIN4Document
        {
            get
            {
                if ((this.mUIInvestigationCaseIN4Document == null))
                {
                    this.mUIInvestigationCaseIN4Document = new UIInvestigationCaseIN4Document(this);
                }
                return this.mUIInvestigationCaseIN4Document;
            }
        }
        #endregion
        
        #region Fields
        private UIInvestigationCaseIN4Document mUIInvestigationCaseIN4Document;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIInvestigationCaseIN4Document : WinControl
    {
        
        public UIInvestigationCaseIN4Document(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Investigation Case: IN40031 - Microsoft Dynamics CRM";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Investigation Case: IN40031 - Microsoft Dynamics CRM - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Instance"] = "5";
                    this.mUIItemCustom.WindowTitles.Add("Investigation Case: IN40031 - Microsoft Dynamics CRM - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIInvestigationMasterCWindow : BrowserWindow
    {
        
        public UIInvestigationMasterCWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                "";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                    "");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public WinTitleBar UIInvestigationMasterCTitleBar
        {
            get
            {
                if ((this.mUIInvestigationMasterCTitleBar == null))
                {
                    this.mUIInvestigationMasterCTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIInvestigationMasterCTitleBar.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                            "");
                    #endregion
                }
                return this.mUIInvestigationMasterCTitleBar;
            }
        }
        
        public UIInvestigationMasterCDocument UIInvestigationMasterCDocument
        {
            get
            {
                if ((this.mUIInvestigationMasterCDocument == null))
                {
                    this.mUIInvestigationMasterCDocument = new UIInvestigationMasterCDocument(this);
                }
                return this.mUIInvestigationMasterCDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIInvestigationMasterCTitleBar;
        
        private UIInvestigationMasterCDocument mUIInvestigationMasterCDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIInvestigationMasterCDocument : HtmlDocument
    {
        
        public UIInvestigationMasterCDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                "";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/SME/main.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://srcrmsme63-ua:5555/SME/main.aspx#376481685";
            this.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                    "");
            #endregion
        }
        
        #region Properties
        public UIContentAreaFrame1 UIContentAreaFrame
        {
            get
            {
                if ((this.mUIContentAreaFrame == null))
                {
                    this.mUIContentAreaFrame = new UIContentAreaFrame1(this);
                }
                return this.mUIContentAreaFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIContentAreaFrame1 mUIContentAreaFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIContentAreaFrame1 : HtmlIFrame
    {
        
        public UIContentAreaFrame1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "contentIFrame1";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "contentIFrame1";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = "Content Area";
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"contentIFrame1\" title=\"Content Are";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                    "");
            #endregion
        }
        
        #region Properties
        public UIHttpsrcrmsme63ua5555Document UIHttpsrcrmsme63ua5555Document
        {
            get
            {
                if ((this.mUIHttpsrcrmsme63ua5555Document == null))
                {
                    this.mUIHttpsrcrmsme63ua5555Document = new UIHttpsrcrmsme63ua5555Document(this);
                }
                return this.mUIHttpsrcrmsme63ua5555Document;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsrcrmsme63ua5555Document mUIHttpsrcrmsme63ua5555Document;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsrcrmsme63ua5555Document : HtmlDocument
    {
        
        public UIHttpsrcrmsme63ua5555Document(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/SME/main.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://srcrmsme63-ua:5555/SME/main.aspx?etc=10051&extraqs=%3fetc%3d10051&pagemode" +
                "=iframe&pagetype=entityrecord";
            this.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                    "");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-crm-Floating-Div";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"ms-crm-Floating-Div\" style=\"width: 1920px; height: 847px; dis" +
                        "play: block; z-index: 2000; opacity: 0;\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "346";
                    this.mUIItemPane.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                            "");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public UILookUpMoreRecordsCustom UILookUpMoreRecordsCustom
        {
            get
            {
                if ((this.mUILookUpMoreRecordsCustom == null))
                {
                    this.mUILookUpMoreRecordsCustom = new UILookUpMoreRecordsCustom(this);
                }
                return this.mUILookUpMoreRecordsCustom;
            }
        }
        
        public HtmlDiv UITestUserPane
        {
            get
            {
                if ((this.mUITestUserPane == null))
                {
                    this.mUITestUserPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUITestUserPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "header_rta_investigatorid_lookupDiv";
                    this.mUITestUserPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUITestUserPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Test User";
                    this.mUITestUserPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUITestUserPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-crm-Lookup ms-crm-InlineLookupEdit";
                    this.mUITestUserPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"ms-crm-Lookup ms-crm-InlineLookupEdit\" id=\"header_rta_investi" +
                        "gatorid_lookupDiv\" role=\"list\" style=\"width: 100%; background-color: rgb(171, 19" +
                        "2, 231);\" ime-mode=\"auto\"";
                    this.mUITestUserPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "33";
                    this.mUITestUserPane.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                            "");
                    #endregion
                }
                return this.mUITestUserPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        
        private UILookUpMoreRecordsCustom mUILookUpMoreRecordsCustom;
        
        private HtmlDiv mUITestUserPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILookUpMoreRecordsCustom : HtmlCustom
    {
        
        public UILookUpMoreRecordsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "item7";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "ms-crm-IL-MenuItem-Lookupmore ms-crm-IL-MenuItem-Lookupmore-Rest";
            this.FilterProperties["ControlDefinition"] = "tabindex=\"0\" class=\"ms-crm-IL-MenuItem-L";
            this.FilterProperties["InnerText"] = "Look Up More Records";
            this.FilterProperties["TagInstance"] = "29";
            this.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                    "");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UILookUpMoreRecordsCustom1
        {
            get
            {
                if ((this.mUILookUpMoreRecordsCustom1 == null))
                {
                    this.mUILookUpMoreRecordsCustom1 = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUILookUpMoreRecordsCustom1.SearchProperties["TagName"] = "A";
                    this.mUILookUpMoreRecordsCustom1.SearchProperties["Id"] = null;
                    this.mUILookUpMoreRecordsCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUILookUpMoreRecordsCustom1.FilterProperties["Class"] = "ms-crm-IL-MenuItem-Anchor-Lookupmore ms-crm-IL-MenuItem-Anchor-Lookupmore-Rest";
                    this.mUILookUpMoreRecordsCustom1.FilterProperties["ControlDefinition"] = "title=\"Look Up More Records\" class=\"ms-c";
                    this.mUILookUpMoreRecordsCustom1.FilterProperties["TagInstance"] = "2";
                    this.mUILookUpMoreRecordsCustom1.WindowTitles.Add("Investigation Master Case: New Investigation Master Case - Microsoft Dynamics CRM" +
                            "");
                    #endregion
                }
                return this.mUILookUpMoreRecordsCustom1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUILookUpMoreRecordsCustom1;
        #endregion
    }
}
